-- 1.What is the total revenue generated by male versus female customers?
select gender ,sum(purchase_amount) as Revenue
from customer
group by gender

-- 2.Which customers used a discount but still spent more than the average purchase amount?

select customer_id,purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount > 
(select avg(purchase_amount) from customer)

-- 3.Which are the top five products with the highest average review rating?

select item_purchased,round(avg(review_rating::numeric),2) as average_review_rating
from customer
group by item_purchased
order by average_review_rating desc
limit 5

-- 4.Compare the average purchase amounts between Standard and Express shipping 

select shipping_type,
round(avg(purchase_amount),2) as avg_purchase_shipping
from customer
group by shipping_type
having shipping_type in ('Standard','Express')

--5.Do subscribed customers spend more ? 
--Compare average spend and total revenue between subscribers and non-subscribers

select subscription_status , 
count(customer_id) as Total_customers,
round(avg(purchase_amount),2) as average_purchase,
sum(purchase_amount) as revenue
from customer
group by subscription_status
order by revenue desc

-- 6.Which five products have the highest percentage of purchases with discounts applied 

select item_purchased ,
round(100*sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer 
group by item_purchased
order by discount_rate desc
limit 5

-- 7.Segment customers into new ,returning and loyal based 
-- on their total number of previous purchases and show the count of each segment

with customer_type as ( 
select customer_id,previous_purchases,
case 
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'loyal'
	end as customer_segment
from customer
)

select customer_segment,count(*)
from customer_type
group by customer_segment
order by count(*) desc

-- What are the top three purchased products within each category?

with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased ,total_orders
from item_counts
where item_rank <= 3

-- Are customers who are repeat buyers (More than five previous purchases) also likely to subscribe?

select subscription_status,
count(*)
from customer
where previous_purchases >5
group by subscription_status

--what is the revenue contribution of each age group?

select  age_group,
sum(purchase_amount) as Revenue
from customer
group by age_group
order by revenue desc;